name: Upload and download artifact or a file from Runner to github repo and to another job
on: 
 push:
  branches:
   - main
jobs:
 uploadArtifactJob:
  runs-on: ubuntu-latest
  steps:
   - name: Create a directory
     run: mkdir -p /tmp
   - name: create a file in the directory
     run: echo "Hello from runner" > /tmp/artifact.txt
   - name: Upload
     uses: actions/upload-artifact@v4
     with:
      name: myartifact
      path: /tmp/artifact.txt
 downloadArtifactjob:
  needs: uploadArtifactJob
  if: failure()
  runs-on: ubuntu-latest
  steps:
   - name: Download artifact from previous Job
     uses: actions/download-artifact@v4
     with:
      name: myartifact
   - name: Check if artifact is downloaded
     run: ls -R 
